In [4]:
import wikipediaapi
import nltk
import pickle 
import numpy as np
from keras.preprocessing.sequence import pad_sequences
from keras.models import load_model
import tensorflow 

# nltk.download('punkt') # at first run
sent_detector = nltk.data.load('tokenizers/punkt/english.pickle')

wiki_wiki = wikipediaapi.Wikipedia(
        language='en',
        extract_format=wikipediaapi.ExtractFormat.WIKI
)

Using TensorFlow backend.


In [5]:
tensorflow.__version__

'1.7.0'

In [6]:
def construct_instance_reasons(statement, section_dict_path, vocab_w2v_path, max_len=-1):
    # Load the vocabulary
    vocab_w2v = pickle.load(open(vocab_w2v_path, 'rb'),encoding='latin1')

    # load the section dictionary.
    section_dict = pickle.load(open(section_dict_path, 'rb'))

    # construct the training data
    X = []
    sections = []
    y = []
    outstring=[]
    
    X_inst = []

    for word in statement:
        if max_len != -1 and len(X_inst) >= max_len:
            continue
        if word not in vocab_w2v:
            X_inst.append(vocab_w2v['UNK'])
        else:
            X_inst.append(vocab_w2v[word])

    # extract the section, and in case the section does not exist in the model, then assign UNK
    section = statement.strip().lower()
    sections.append(np.array([section_dict[section] if section in section_dict else 0]))

    X.append(X_inst)
    outstring.append(statement)
    #entity_id  revision_id timestamp   entity_title    section_id  section prg_idx sentence_idx    statement   citations

    X = pad_sequences(X, maxlen=max_len, value=vocab_w2v['UNK'], padding='pre')

    return X, np.array(sections), outstring

In [7]:
p_wiki = wiki_wiki.page("RM (rapper)")

In [15]:
p_wiki.text

'Kim Nam-joon (Korean: 김남준; born September 12, 1994), better known as RM (formerly Rap Monster), is a South Korean rapper, songwriter, and record producer. He is the leader and the main rapper in the South Korean boy group BTS, managed under Big Hit Entertainment. In 2015, he released his first solo mixtape, RM. As of October 2018, his second mixtape, Mono, is the highest charting album by a Korean soloist on the Billboard 200 chart, having peaked at 26.  He has recorded with artists such as Wale, Warren G, Gaeko, Krizz Kaliko, MFBTY, Fall Out Boy, Primary, and Lil Nas X.\n\nEarly life\nKim Nam-joon was born on September 12, 1994, in Dongjak-gu, South Korea, and grew up in Ilsan-gu, where his family moved when he was five. He is the elder of two siblings and has a younger sister.As a child, RM largely learned English through watching Friends with his mother. As a student, he actively wrote poetry and often received awards for his writings. He posted his work to an online poetry website

In [8]:
path_model = "models/fa_en_model_rnn_attention_section.h5"
model = load_model(path_model)

# load the data




/home/livia/Documentos/miniconda3/envs/article/lib/python3.6/site-packages/keras/engine/topology.py:1271: UserWarning: The `Merge` layer is deprecated and will be removed after 08/2017. Use instead layers from `keras.layers.merge`, e.g. `add`, `concatenate`, etc.
  return cls(**config)


In [45]:
p_wiki.text.split(' ')

['Kim',
 'Nam-joon',
 '(Korean:',
 '김남준;',
 'born',
 'September',
 '12,',
 '1994),',
 'better',
 'known',
 'as',
 'RM',
 '(formerly',
 'Rap',
 'Monster),',
 'is',
 'a',
 'South',
 'Korean',
 'rapper,',
 'songwriter,',
 'and',
 'record',
 'producer.',
 'He',
 'is',
 'the',
 'leader',
 'and',
 'the',
 'main',
 'rapper',
 'in',
 'the',
 'South',
 'Korean',
 'boy',
 'group',
 'BTS,',
 'managed',
 'under',
 'Big',
 'Hit',
 'Entertainment.',
 'In',
 '2015,',
 'he',
 'released',
 'his',
 'first',
 'solo',
 'mixtape,',
 'RM.',
 'As',
 'of',
 'October',
 '2018,',
 'his',
 'second',
 'mixtape,',
 'Mono,',
 'is',
 'the',
 'highest',
 'charting',
 'album',
 'by',
 'a',
 'Korean',
 'soloist',
 'on',
 'the',
 'Billboard',
 '200',
 'chart,',
 'having',
 'peaked',
 'at',
 '26.',
 '',
 'He',
 'has',
 'recorded',
 'with',
 'artists',
 'such',
 'as',
 'Wale,',
 'Warren',
 'G,',
 'Gaeko,',
 'Krizz',
 'Kaliko,',
 'MFBTY,',
 'Fall',
 'Out',
 'Boy,',
 'Primary,',
 'and',
 'Lil',
 'Nas',
 'X.\n\nEarly',
 'lif

In [65]:
acc = ''
acc2= ''
bo = False
for word in p_wiki.text.split(' '):
    if '\n' in word and not bo:
        if word.count('\n') ==1 and acc2 == '':
            sp = word.split('\n')
            acc += sp[0]
            acc = ''

        elif word.count('\n') <= 2:
            bo = True
            acc2+=word.split('\n')[2] + ' '
            
    elif '\n' in word and bo:
        bo = False
        acc2+=word.split('\n')[0]+ ' '
        acc2=''
    elif  bo:
        acc2+=word+ ' '
    else:
        acc += word + ' '


here3
here3
here3
here3
here3
here3
here3
here3
here3
here3
here3
here3
here3
here3
here3
here3
here3
here3
here3
here3
here3
here3
here3
here3
here3
here3
here3
here3
here3
here3
here3
here3
here3
here3
here3
here3
here3
here3
here3
here3
here3
here3
here3
here3
here3
here3
here3
here3
here3
here3
here3
here3
here3
here3
here3
here3
here3
here3
here3
here3
here3
here3
here3
here3
here3
here3
here3
here3
here3
here3
here3
here3
here3
here3
here3
here3
here3
here3
here3
here3
here3
here3
here3
here3
here3
here3
here3
here3
here3
here3
here3
here3
here3
here3
here3
here3
here3
here3
here3
here3
here3
here1
Early life 
here3
here3
here3
here3
here3
here3
here3
here3
here3
here3
here3
here3
here3
here3
here3
here3
here3
here3
here3
here3
here3
here3
here3
here3
here3
here3
here3
here3
here3
here3
here3
here3
here3
here3
here3
here3
here3
here3
here3
here3
here3
here3
here3
here3
here3
here3
here3
here3
here3
here3
here3
here3
here3
here3
here3
here3
here3
here3
here3
here3
here3
here3
here

In [37]:
p_wiki.text.split(' ')

['Kim',
 'Nam-joon',
 '(Korean:',
 '김남준;',
 'born',
 'September',
 '12,',
 '1994),',
 'better',
 'known',
 'as',
 'RM',
 '(formerly',
 'Rap',
 'Monster),',
 'is',
 'a',
 'South',
 'Korean',
 'rapper,',
 'songwriter,',
 'and',
 'record',
 'producer.',
 'He',
 'is',
 'the',
 'leader',
 'and',
 'the',
 'main',
 'rapper',
 'in',
 'the',
 'South',
 'Korean',
 'boy',
 'group',
 'BTS,',
 'managed',
 'under',
 'Big',
 'Hit',
 'Entertainment.',
 'In',
 '2015,',
 'he',
 'released',
 'his',
 'first',
 'solo',
 'mixtape,',
 'RM.',
 'As',
 'of',
 'October',
 '2018,',
 'his',
 'second',
 'mixtape,',
 'Mono,',
 'is',
 'the',
 'highest',
 'charting',
 'album',
 'by',
 'a',
 'Korean',
 'soloist',
 'on',
 'the',
 'Billboard',
 '200',
 'chart,',
 'having',
 'peaked',
 'at',
 '26.',
 '',
 'He',
 'has',
 'recorded',
 'with',
 'artists',
 'such',
 'as',
 'Wale,',
 'Warren',
 'G,',
 'Gaeko,',
 'Krizz',
 'Kaliko,',
 'MFBTY,',
 'Fall',
 'Out',
 'Boy,',
 'Primary,',
 'and',
 'Lil',
 'Nas',
 'X.\n\nEarly',
 'lif

In [9]:
organized_text = []
predictions_text = []
max_seq_length = model.input[0].shape[1].value

for s in p_wiki.sections:
    stripped_text = sent_detector.tokenize(s.text.strip())
    organized_text.append((s.title, stripped_text))
    for phrase in stripped_text:
        X, sections, outstring = construct_instance_reasons(phrase, "embeddings/word_dict_en.pck", "embeddings/section_dict_en.pck", max_seq_length)
        pred = model.predict([X, sections])
        predictions_text.append((pred, phrase))
        print(pred)

[[9.9985206e-01 1.4628991e-04]]
[[9.9985206e-01 1.4628991e-04]]
[[9.9985206e-01 1.4628991e-04]]
[[9.9985206e-01 1.4628991e-04]]
[[9.9985206e-01 1.4628991e-04]]
[[9.9985206e-01 1.4628991e-04]]
[[9.9985206e-01 1.4628991e-04]]
[[9.9985206e-01 1.4628991e-04]]
[[9.9985206e-01 1.4628991e-04]]
[[9.9985206e-01 1.4628991e-04]]
[[9.9985206e-01 1.4628991e-04]]
[[9.9985206e-01 1.4628991e-04]]
[[9.9985206e-01 1.4628991e-04]]
[[9.9985206e-01 1.4628991e-04]]
[[9.9985206e-01 1.4628991e-04]]
[[9.9985206e-01 1.4628991e-04]]
[[9.9985206e-01 1.4628991e-04]]
[[9.9985206e-01 1.4628991e-04]]
[[9.9985206e-01 1.4628991e-04]]
[[9.9985206e-01 1.4628991e-04]]
[[9.9985206e-01 1.4628991e-04]]
[[9.9985206e-01 1.4628991e-04]]
[[9.9985206e-01 1.4628991e-04]]
[[9.9985206e-01 1.4628991e-04]]
[[9.9985206e-01 1.4628991e-04]]
[[9.9985206e-01 1.4628991e-04]]
[[9.9985206e-01 1.4628991e-04]]
[[9.9985206e-01 1.4628991e-04]]
[[9.9985206e-01 1.4628991e-04]]


In [11]:
for e in predictions_text:
    print(e[1])

Kim Nam-joon was born on September 12, 1994, in Dongjak-gu, South Korea, and grew up in Ilsan-gu, where his family moved when he was five.
He is the elder of two siblings and has a younger sister.As a child, RM largely learned English through watching Friends with his mother.
As a student, he actively wrote poetry and often received awards for his writings.
He posted his work to an online poetry website for roughly one year, where he received moderate attention.
Through this, RM grew interested in pursuing a literary career but decided against it.
At the age of 11, RM became interested in hip-hop music after hearing Epik High's "Fly" in fifth grade.
He found that the song had provided him comfort, and, due to this, decided to look further into the genre.
Following an introduction to American rapper Eminem by his school teacher, RM grew interested in lyricism, printing lyrics he felt were "cool" and sharing them with his friends.
RM transitioned to writing lyrics then, stating that his 